# Generated by Django 5.2.7 on 2025-10-20 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=100)),
                ('creado', models.DateTimeField()),
                ('actualizado', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Item_Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=1, max_digits=10)),
                ('descripcion', models.CharField(max_length=200)),
                ('valor_unitario', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('igv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Baja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_baja', models.DateField()),
                ('fecha_emision', models.DateField()),
                ('lote', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('ticket_sunat', models.CharField(max_length=100)),
                ('denominacion', models.CharField(max_length=100)),
                ('digest_value', models.TextField()),
                ('signature_value', models.TextField()),
                ('enviada_sunat', models.BooleanField(default=False)),
                ('aceptada_sunat', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
