# Generated by Django 5.2.7 on 2026-01-27 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PR', 'Propietario'), ('AD', 'Administrador'), ('EM', 'Empleado'), ('PA', 'Administrador de la plataforma')], default='EM', max_length=2)),
                ('employee_id', models.CharField(blank=True, help_text='ID de empleado en el negocio', max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el perfil está activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, help_text='Obligatorio para todos los roles excepto Administrador de la plataforma', null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.business')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'constraints': [models.UniqueConstraint(condition=models.Q(('business__isnull', False)), fields=('user', 'business'), name='unique_user_business')],
            },
        ),
    ]
