# Generated by Django 5.2.7 on 2026-02-28 17:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessSunatConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_id', models.CharField(max_length=100)),
                ('persona_token', models.CharField(max_length=200)),
                ('production_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sunat_config', to='operations.business')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('0', 'SIN DOC'), ('1', 'DNI'), ('4', 'CE'), ('6', 'RUC'), ('7', 'PASAPORTE')], max_length=2)),
                ('doc_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='operations.business')),
            ],
        ),
        migrations.CreateModel(
            name='SunatDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('SALE', 'Venta'), ('PURCHASE', 'Compra')], default='SALE', max_length=10)),
                ('series', models.CharField(max_length=10)),
                ('number', models.PositiveIntegerField()),
                ('issue_date', models.DateField()),
                ('currency', models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares')], default='PEN', max_length=3)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('payment_term', models.CharField(choices=[('CASH', 'Contado'), ('CREDIT', 'Crédito')], default='CASH', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('total_taxable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_igv', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ISSUED', 'Emitido'), ('VOID', 'Anulado')], default='DRAFT', max_length=10)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sunat_documents', to='operations.business')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='taxes.documenttype')),
                ('order', models.OneToOneField(blank=True, help_text='Si el comprobante se generó desde un pedido.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sunat_document', to='operations.order')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='taxes.party')),
                ('ref_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referenced_by', to='taxes.sunatdocument')),
            ],
        ),
        migrations.CreateModel(
            name='SunatDocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_affectation', models.CharField(choices=[('10', 'Gravado - Operación Onerosa (IGV)'), ('20', 'Exonerado'), ('30', 'Inafecto'), ('21', 'Gratuito (referencial)')], default='10', max_length=2)),
                ('igv_rate', models.DecimalField(decimal_places=4, default=Decimal('0.1800'), max_digits=5)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='taxes.sunatdocument')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sunat_items', to='operations.product')),
            ],
        ),
        migrations.CreateModel(
            name='SunatSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production', models.BooleanField(default=False)),
                ('file_name', models.CharField(help_text='Formato típico: RUC-TIPO-SERIE-NUMERO', max_length=80)),
                ('apisunat_document_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACCEPTED', 'Aceptado'), ('REJECTED', 'Rechazado'), ('EXCEPTION', 'Excepción'), ('ERROR', 'Error interno')], default='PENDING', max_length=12)),
                ('xml_url', models.URLField(blank=True, max_length=500, null=True)),
                ('cdr_url', models.URLField(blank=True, max_length=500, null=True)),
                ('sunat_issued_at', models.DateTimeField(blank=True, null=True)),
                ('sunat_responded_at', models.DateTimeField(blank=True, null=True)),
                ('faults', models.JSONField(blank=True, null=True)),
                ('notes', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('raw_request', models.JSONField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='taxes.sunatdocument')),
            ],
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['business', 'doc_type', 'doc_number'], name='taxes_party_busines_c6cb8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(fields=('business', 'doc_type', 'doc_number'), name='uq_party_business_doctype_docnumber'),
        ),
        migrations.AddIndex(
            model_name='sunatdocument',
            index=models.Index(fields=['business', 'issue_date'], name='taxes_sunat_busines_bc4a80_idx'),
        ),
        migrations.AddIndex(
            model_name='sunatdocument',
            index=models.Index(fields=['business', 'document_type', 'series', 'number'], name='taxes_sunat_busines_ab3bac_idx'),
        ),
        migrations.AddConstraint(
            model_name='sunatdocument',
            constraint=models.UniqueConstraint(fields=('business', 'direction', 'document_type', 'series', 'number'), name='uq_sunatdoc_business_dir_type_series_number'),
        ),
    ]
